/** Staff roles do not grant platform access or permission administration. */
export const DEFAULT_STAFF_ROLES = [
  {
    name: "ผู้จัดการหอพัก",
    description:
      "ดูแลห้อง ผู้เช่า บิล สลิป และสมาชิกทีมภายในสาขาที่ได้รับสิทธิ์",
    keys: [
      "branch.view",
      "property.view",
      "property.create",
      "property.update",
      "room.view",
      "room.create",
      "room.update",
      "room.transfer",
      "resident.view",
      "resident.create",
      "resident.update",
      "contract.view",
      "contract.create",
      "contract.update",
      "contract.invite",
      "meter.view",
      "meter.create",
      "meter.update",
      "invoice.view",
      "invoice.create",
      "invoice.update",
      "invoice.issue",
      "payment.view",
      "payment.approve",
      "notification.send",
      "settings.view",
      "settings.update",
      "report.view",
      "report.export",
      "user.view",
      "user.create",
      "user.update",
    ],
  },
  {
    name: "การเงิน",
    description: "ออกบิล ตรวจสลิป และส่งออกรายงานการเงินในสาขาที่ได้รับสิทธิ์",
    keys: [
      "branch.view",
      "property.view",
      "room.view",
      "resident.view",
      "contract.view",
      "meter.view",
      "invoice.view",
      "invoice.create",
      "invoice.update",
      "invoice.issue",
      "payment.view",
      "payment.approve",
      "notification.send",
      "settings.view",
      "report.view",
      "report.export",
    ],
  },
  {
    name: "ดูรายงาน",
    description: "ดูข้อมูลห้อง ผู้เช่า บิล และรายงาน โดยแก้ไขหรืออนุมัติไม่ได้",
    keys: [
      "branch.view",
      "property.view",
      "room.view",
      "resident.view",
      "invoice.view",
      "payment.view",
      "report.view",
      "report.export",
    ],
  },
] as const;
