import { Type } from 'class-transformer';
import { ArrayMinSize, IsDateString, IsEnum, IsInt, IsNumber, IsObject, IsOptional, IsPositive, IsString, Max, Min, ValidateNested } from 'class-validator';
import { MeterType } from '@prisma/client';

export class CreateMeterReadingDto { @IsString() roomId!: string; @IsEnum(MeterType) type!: MeterType; @IsDateString() readingDate!: string; @Type(() => Number) @IsNumber() @Min(0) previousValue!: number; @Type(() => Number) @IsNumber() @Min(0) currentValue!: number; @Type(() => Number) @IsNumber() @Min(0) unitRate!: number; @IsOptional() @IsString() imageUrl?: string; }
export class InvoiceMeterReadingDto { @IsEnum(MeterType) type!: MeterType; @IsDateString() readingDate!: string; @Type(() => Number) @IsNumber() @Min(0) previousValue!: number; @Type(() => Number) @IsNumber() @Min(0) currentValue!: number; @Type(() => Number) @IsNumber() @Min(0) unitRate!: number; }
export class CreateBillingPeriodDto { @Type(() => Number) @IsInt() @Min(2020) year!: number; @Type(() => Number) @IsInt() @Min(1) @Max(12) month!: number; @IsDateString() dueDate!: string; }
export class InvoiceItemDto { @IsString() code!: string; @IsString() description!: string; @Type(() => Number) @IsNumber() @IsPositive() quantity!: number; @Type(() => Number) @IsNumber() @Min(0) unitPrice!: number; @IsOptional() @IsObject() metadata?: Record<string, unknown>; }
export class CreateInvoiceDto { @IsString() branchId!: string; @IsString() periodId!: string; @IsString() contractId!: string; @IsString() number!: string; @Type(() => Number) @IsNumber() @Min(0) discount = 0; @ArrayMinSize(1) @ValidateNested({ each: true }) @Type(() => InvoiceItemDto) items!: InvoiceItemDto[]; @IsOptional() @ValidateNested({ each: true }) @Type(() => InvoiceMeterReadingDto) meterReadings?: InvoiceMeterReadingDto[]; }
